### ISSUE TITLE
Iterating on our message handling

### ISSUE THREAD

**Issue by rgbkrk** [nteract/jupyter-display-area#25]
Currently, the way that `handle(msg)` works is a `switch` statement on the message type.

``` JavaScript
handle(msg) {
        var json = {};
        var msg_type = json.output_type = msg.header.msg_type;
        var content = msg.content;
        switch (msg_type) {
            case 'clear_output':
                // msg spec v4 had stdout, stderr, display keys
                // v4.1 replaced these with just wait
                // The default behavior is the same (stdout=stderr=display=True, wait=False),
                // so v4 messages will still be properly handled,
                // except for the rarely used clearing less than all output.
                this.clearOutput(msg.content.wait || false);
                return;
            case 'stream':
                json.text = content.text;
                json.name = content.name;
                break;
            case 'display_data':
                json.data = content.data;
                json.metadata = content.metadata;
                break;
            case 'execute_result':
                json.data = content.data;
                json.metadata = content.metadata;
                json.execution_count = content.execution_count;
                break;
            case 'error':
                json.ename = content.ename;
                json.evalue = content.evalue;
                json.traceback = content.traceback;
                break;
            case 'status':
            case 'execute_input':
                // Explicit ignore of status changes and input
                return false;
            default:
                console.log('unhandled output message', msg);
                return false;
        }
        return this.appendOutput(json);
    }
```

This also shows some of the awkward inconsistency in how we work across streams, tracebacks, display_data, and a few others (as far as data type and action are concerned). That's not this discussion, though it probably has some relations.

An alternative way might be to use [an EventEmitter](https://nodejs.org/api/events.html). Browserify _does_ [adapt node events](https://github.com/substack/browserify-handbook#builtins).

``` javascript
// Set up the default actions
this.dispatch.on('display_data', msg => {
  this.appendOutput({
    data: msg.content.data,
    metadata: msg.content.metadata
  });
})
this.dispatch.on('execute_result', ...)
```

Replacing the current `handle(msg)`:

``` javascript
handle(msg) {
  if(! msg.header || !msg.header.msg_type) {
    return;
  }

  var msg_type = msg.header.msg_type;
  this.dispatch.emit(msg_type, msg);
}
```

Which should then make you wonder why we handle(msg) and not another `.on('jupyter_message',...)`.

/cc @jdfreder @willwhitney

**Comment by rgbkrk** [comment]
The follow up question to the Evented approach is [how errors get handled](https://nodejs.org/api/events.html#events_class_events_eventemitter):

> When an EventEmitter instance experiences an error, the typical action is to emit an 'error' event. Error events are treated as a special case in node. If there is no listener for it, then the default action is to print a stack trace and exit the program.

**Comment by rgbkrk** [comment]
By the way... this discussion is meant for the broader output area discussion, not just this prototypal web component.

**Comment by rgbkrk** [comment]
@jdfreder how compatible are these with Backbone.Events? It seems the same.

**Comment by willwhitney** [comment]
This sounds good to me as far as internal architecture. For React usage like in the [Atom Notebook](https://github.com/willwhitney/jupyter-notebook-atom), there just needs to be some way to declaratively state what messages it should be displaying. That could look like either 1) a constructor that takes a list of messages to display, or much better 2) a `setMessages` method which diffs its current messages and the ones passed as an argument, then updates the display accordingly.

More generally, we should keep in mind that in most applications this is not the direct receiver of these messages. For example, in Hydrogen messages need to be received at a higher level of the application in order to update the kernel status indicator. That implies that we shouldn't think of this component as having a lot of internal state storage, but that instead it should be slaved to the state of the larger application.

Dream interface in React + JSX:

```html
<jupyter-display-area messages={this.props.messages} />
```

Or in something data-binding-ey like Angular (don't trust me on this I don't use Angular):

```html
<jupyter-display-area ng-model="cell.messages">
```

**Comment by willwhitney** [comment]
Do people still use Backbone?

**Comment by rgbkrk** [comment]
The widgets use Backbone and is a really nice interface between data and events emitted between a running backend/kernel and user interactions. Backbone plays well with both [React](https://www.youtube.com/watch?v=QqSHrpro02g) and [Web Components](https://www.youtube.com/watch?v=dztuKgjk0Bg).

I think it makes sense for users to use it, I'm not saying we use it in any way. That was a curiosity for Jon.

**Comment by willwhitney** [comment]
Haha, sorry for the snark. It's not actually very different than the Store & Dispatcher roles in Flux.

**Comment by rgbkrk** [comment]
Closing since we're now using the react display area bundled into nteract/nteract.
